runtime: java 
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
handlers:
- url: /
  script: this field is required, but ignored 
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 180
liveness_check:
  path: "/"
  check_interval_sec: 100
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2  